config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "user/registrations"}
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'

  get 'search_funds', to: 'funds#search'
  resources :user_funds, only: [:create, :destroy]

  get 'my_friends', to: 'users#my_friends'
  resources :users, only: [:show]
  resources :friendships

  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/fund.rb
class Fund < ApplicationRecord
  has_many :user_funds
  has_many :users, through: :user_funds


  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end


  def self.new_from_lookup(ticker_symbol)
    begin
      client = IEX::Api::Client.new(publishable_token: 'pk_4daaaaa6c0684adba98a9eae624164a7')
      looked_up_stock = client.quote(ticker_symbol)
      new(name: looked_up_stock.company_name,
          ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price)
    rescue Exception => e
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_funds
  has_many :funds, through: :user_funds

  has_many :friendships
  has_many :friends, through: :friendships

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end


  def fund_already_added?(ticker_symbol)
    fund = Fund.find_by_ticker(ticker_symbol)
    return false unless fund
    user_funds.where(fund_id: fund.id).exists?
  end

  def under_fund_limit?
    (user_funds.count < 10)
  end

  def can_add_fund?(ticker_symbol)
    under_fund_limit? && !fund_already_added?(ticker_symbol)
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end

end

app/models/user_fund.rb
class UserFund < ApplicationRecord
  belongs_to :user
  belongs_to :fund
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice] = "Friend was deleted!"
    redirect_to my_friends_path
  end

end

app/controllers/funds_controller.rb
class FundsController < ApplicationController

  def search
    if params[:fund].blank?
      flash.now[:danger] = "You have entered an empty search string."
    else
      @fund = Fund.new_from_lookup(params[:fund])
      flash.now[:danger] = "No stock matches your search criteria." unless @fund
    end
    respond_to do |format|
      format.js {render partial: 'users/result'}
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/user_funds_controller.rb
class UserFundsController < ApplicationController

  def create
    fund = Fund.find_by_ticker(params[:fund_ticker])
    if fund.blank?
      fund = Fund.new_from_lookup(params[:fund_ticker])
      fund.save
    end
    @user_fund = UserFund.create(user: current_user, fund: fund)
    flash[:success] = "Added #{@user_fund.fund.name} successfully!"
    redirect_to my_portfolio_path
  end

  def destroy
    fund = Fund.find(params[:id])
    @user_fund = UserFund.where(user_id: current_user.id, fund_id: fund.id).first
    @user_fund.destroy
    flash[:notice] = "Stock was successfully removed."
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @user = current_user
    @user_funds = current_user.funds
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    if params[:search_param].blank?
      flash.now[:danger] = "You have entered an empty search string."
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = "No users match your search criteria." if @users.blank?
    end
    respond_to do |format|
      format.js {render partial: 'friends/result'}
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)
    if current_user.save
      flash[:success] = "Friend was successfully added!"
    else
      flash[:danger] = "There was something wrong."
    end
    redirect_to my_friends_path
  end

  def show
    @user = User.find(params[:id])
    @user_funds = @user.funds
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_funds_helper.rb
module UserFundsHelper
end

app/views/friends/_lookup.html.erb
<h1>My Friends </h1>

<h3>Search for Friends</h3>
<div id="friend-lookup">
  <%= form_tag search_friends_path, remote: true, method: :get, id: "friend-lookup-form" do %>
  <div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <%= text_field_tag :search_param, params[:search_param], placeholder: "Enter Name or Email", autofocus: true,
                                 class: "form-control search-box input-lg" %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn btn'lg btn-success") do %>
      <i class="glyphicon glyphicon-search"></i>  Search
      <% end %>
    </div>
  </div>
  <% end %>
</div>
<div id="results">
  <%= render 'friends/result' %>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<% if @users %>
  <% if @users.size > 0 %>
    <div id="friend-lookup-results" class="well results-block col-md-10">
      <table class="search-results-table col-md-12">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><strong>Name: </strong> <%= user.full_name %></td>
              <td><strong>Email: </strong> <%= user.email %></td>
              <td><strong>Profile: </strong> <%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success" %>
                  <% if current_user.not_friends_with?(user.id) %>
                    <%= link_to "Add Friend", add_friend_path(user: current_user, friend: user),
                    class: "btn btn-xs btn-success", method: :post %>
                  <% else %>
                    <span class="label label-primary">
                      Friend
                    </span>
                  <% end %>
                </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html') %>")

app/views/funds/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_funds.each do |user_fund| %>
      <tr>
        <td><%= user_fund.name %></td>
        <td><%= user_fund.ticker %></td>
        <td><%= user_fund.last_price %></td>
        <% if @user.id == current_user.id %>
          <td><%= link_to "Delete This Stock", user_fund_path(user_fund), method: :delete,
                                               data: {confirm: "Are you sure?"},
                                               class: "btn btn-xs btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <%= link_to 'StockTracker', root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6">
          <li><%= link_to "My Portfolio", my_portfolio_path %></li>
          <li><%= link_to "My Profile", edit_registration_path(current_user) %></li>
          <li><%= link_to "My Friends", my_friends_path %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class="col-md-4 logout">
            <%= link_to("logout", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete) %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stock" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<% if @fund %>
  <div class="well results-block">
    <strong>Symbol: </strong><%= @fund.ticker %>
    <strong>Name: </strong><%= @fund.name %>
    <strong>Price: </strong><%= @fund.last_price %>
    <% if current_user.can_add_fund?(@fund.ticker) %>
      <%= link_to "Add to My Stocks", user_funds_path(user: current_user, fund_ticker: @fund.ticker),
                                      class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="label label-default">
        Stock cannot be added because you have already added
        <% if !current_user.under_fund_limit? %>
          10 stocks
        <% end %>
        <% if current_user.fund_already_added?(@fund.ticker) %>
          this stock
        <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html') %>")

app/views/users/my_friends.html.erb
<%= render 'friends/lookup' %>

<% if @friendships.size > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="3" class="page-header">
          <h2>My Friends</h2>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friendships.each do |friend| %>
        <tr>
          <td><%= friend.full_name %></td>
          <td><%= friend.email %></td>
          <td><%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %></td>
            <td><%= link_to "Remove Friend", friendship_path(friend), method: :delete,
                                                 data: {confirm: "Are you sure?"},
                                                 class: "btn btn-xs btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="row col-lg-12">
    <p class="lead">You don't have any friends yet. Please add some!</p>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio </h1>

<h3>Search for Stocks</h3>
<div id="stock-lookup">
  <%= form_tag search_funds_path, remote: true, method: :get, id: "stock-lookup-form" do %>
  <div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <%= text_field_tag :fund, params[:fund], placeholder: "Stock Ticker Symbol", autofocus: true,
                                 class: "form-control search-box input-lg" %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn btn'lg btn-success") do %>
      <i class="glyphicon glyphicon-search"></i>  Look up a stock
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<div id="results">
  <%= render 'users/result' %>
</div>

<%= render 'funds/list' %>

app/views/users/show.html.erb
<h2>User Details</h2>

<dl class="dl-horizontal">
  <dt><strong>Full Name</strong></dt>
    <dd><%= @user.full_name %></dd>
  <dt><strong>Email</strong></dt>
    <dd><%= @user.email %></dd>
</dl>

<% if @user.funds.size > 0 %>
  <%= render "funds/list" %>
<% else %>
  <p class="lead">This user is not tracking any stocks.</p>
<% end %>

<%= link_to "Back", my_friends_path, class: "btn btn-primary" %>

app/views/welcome/index.html.erb
<h1>Welcome to the Finance Tracker App</h1>

<%= link_to "Log Out", destroy_user_session_path, method: :delete %>